version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_DATABASE_URL: ${DIRECT_DATABASE_URL}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB} 
    image: app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    volumes:
      - ./src:/usr/app/src

  postgresdb:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgres:15.5
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  db-logs:
networks:
  app-network:
    driver: bridge

