FROM postgres:15-alpine
RUN ["mkdir", "var/log/postgressql"]
RUN ["chown", "postgres:postgres", "var/log/postgressql"]
CMD ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgressql"]